// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_settings_var
int set_settings_var(std::string name, NumericVector value);
RcppExport SEXP _epicR_set_settings_var(SEXP nameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(set_settings_var(name, value));
    return rcpp_result_gen;
END_RCPP
}
// get_settings
List get_settings();
RcppExport SEXP _epicR_get_settings() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_settings());
    return rcpp_result_gen;
END_RCPP
}
// get_agent_size_bytes
int get_agent_size_bytes();
RcppExport SEXP _epicR_get_agent_size_bytes() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_agent_size_bytes());
    return rcpp_result_gen;
END_RCPP
}
// get_runtime_stats
List get_runtime_stats();
RcppExport SEXP _epicR_get_runtime_stats() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_runtime_stats());
    return rcpp_result_gen;
END_RCPP
}
// get_progress
int get_progress();
RcppExport SEXP _epicR_get_progress() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_progress());
    return rcpp_result_gen;
END_RCPP
}
// get_agent
List get_agent(long id);
RcppExport SEXP _epicR_get_agent(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(get_agent(id));
    return rcpp_result_gen;
END_RCPP
}
// get_smith
List get_smith();
RcppExport SEXP _epicR_get_smith() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_smith());
    return rcpp_result_gen;
END_RCPP
}
// create_agents
int create_agents();
RcppExport SEXP _epicR_create_agents() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(create_agents());
    return rcpp_result_gen;
END_RCPP
}
// allocate_resources
int allocate_resources();
RcppExport SEXP _epicR_allocate_resources() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(allocate_resources());
    return rcpp_result_gen;
END_RCPP
}
// Cget_pointers
List Cget_pointers();
RcppExport SEXP _epicR_Cget_pointers() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(Cget_pointers());
    return rcpp_result_gen;
END_RCPP
}
// deallocate_resources
int deallocate_resources();
RcppExport SEXP _epicR_deallocate_resources() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(deallocate_resources());
    return rcpp_result_gen;
END_RCPP
}
// init_session_internal
int init_session_internal();
RcppExport SEXP _epicR_init_session_internal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(init_session_internal());
    return rcpp_result_gen;
END_RCPP
}
// model_run
int model_run(int max_n_agents);
RcppExport SEXP _epicR_model_run(SEXP max_n_agentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type max_n_agents(max_n_agentsSEXP);
    rcpp_result_gen = Rcpp::wrap(model_run(max_n_agents));
    return rcpp_result_gen;
END_RCPP
}
// get_event
List get_event(int i);
RcppExport SEXP _epicR_get_event(SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(get_event(i));
    return rcpp_result_gen;
END_RCPP
}
// get_n_events
int get_n_events();
RcppExport SEXP _epicR_get_n_events() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_n_events());
    return rcpp_result_gen;
END_RCPP
}
// get_agent_events
DataFrame get_agent_events(int id);
RcppExport SEXP _epicR_get_agent_events(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(get_agent_events(id));
    return rcpp_result_gen;
END_RCPP
}
// get_events_by_type
DataFrame get_events_by_type(int event_type);
RcppExport SEXP _epicR_get_events_by_type(SEXP event_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type event_type(event_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_events_by_type(event_type));
    return rcpp_result_gen;
END_RCPP
}
// get_all_events
DataFrame get_all_events();
RcppExport SEXP _epicR_get_all_events() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_all_events());
    return rcpp_result_gen;
END_RCPP
}
// get_all_events_matrix
NumericMatrix get_all_events_matrix();
RcppExport SEXP _epicR_get_all_events_matrix() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_all_events_matrix());
    return rcpp_result_gen;
END_RCPP
}
// get_inputs
List get_inputs();
RcppExport SEXP _epicR_get_inputs() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_inputs());
    return rcpp_result_gen;
END_RCPP
}
// set_input_var
int set_input_var(std::string name, NumericVector value);
RcppExport SEXP _epicR_set_input_var(SEXP nameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(set_input_var(name, value));
    return rcpp_result_gen;
END_RCPP
}
// get_sample_output
double get_sample_output(int year, int sex);
RcppExport SEXP _epicR_get_sample_output(SEXP yearSEXP, SEXP sexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    Rcpp::traits::input_parameter< int >::type sex(sexSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sample_output(year, sex));
    return rcpp_result_gen;
END_RCPP
}
// get_output
List get_output();
RcppExport SEXP _epicR_get_output() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_output());
    return rcpp_result_gen;
END_RCPP
}
// get_output_ex
List get_output_ex();
RcppExport SEXP _epicR_get_output_ex() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_output_ex());
    return rcpp_result_gen;
END_RCPP
}
// mvrnormArma
arma::mat mvrnormArma(int n, arma::vec mu, arma::mat sigma);
RcppExport SEXP _epicR_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Xrexp
NumericVector Xrexp(int n, double rate);
RcppExport SEXP _epicR_Xrexp(SEXP nSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(Xrexp(n, rate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_epicR_set_settings_var", (DL_FUNC) &_epicR_set_settings_var, 2},
    {"_epicR_get_settings", (DL_FUNC) &_epicR_get_settings, 0},
    {"_epicR_get_agent_size_bytes", (DL_FUNC) &_epicR_get_agent_size_bytes, 0},
    {"_epicR_get_runtime_stats", (DL_FUNC) &_epicR_get_runtime_stats, 0},
    {"_epicR_get_progress", (DL_FUNC) &_epicR_get_progress, 0},
    {"_epicR_get_agent", (DL_FUNC) &_epicR_get_agent, 1},
    {"_epicR_get_smith", (DL_FUNC) &_epicR_get_smith, 0},
    {"_epicR_create_agents", (DL_FUNC) &_epicR_create_agents, 0},
    {"_epicR_allocate_resources", (DL_FUNC) &_epicR_allocate_resources, 0},
    {"_epicR_Cget_pointers", (DL_FUNC) &_epicR_Cget_pointers, 0},
    {"_epicR_deallocate_resources", (DL_FUNC) &_epicR_deallocate_resources, 0},
    {"_epicR_init_session_internal", (DL_FUNC) &_epicR_init_session_internal, 0},
    {"_epicR_model_run", (DL_FUNC) &_epicR_model_run, 1},
    {"_epicR_get_event", (DL_FUNC) &_epicR_get_event, 1},
    {"_epicR_get_n_events", (DL_FUNC) &_epicR_get_n_events, 0},
    {"_epicR_get_agent_events", (DL_FUNC) &_epicR_get_agent_events, 1},
    {"_epicR_get_events_by_type", (DL_FUNC) &_epicR_get_events_by_type, 1},
    {"_epicR_get_all_events", (DL_FUNC) &_epicR_get_all_events, 0},
    {"_epicR_get_all_events_matrix", (DL_FUNC) &_epicR_get_all_events_matrix, 0},
    {"_epicR_get_inputs", (DL_FUNC) &_epicR_get_inputs, 0},
    {"_epicR_set_input_var", (DL_FUNC) &_epicR_set_input_var, 2},
    {"_epicR_get_sample_output", (DL_FUNC) &_epicR_get_sample_output, 2},
    {"_epicR_get_output", (DL_FUNC) &_epicR_get_output, 0},
    {"_epicR_get_output_ex", (DL_FUNC) &_epicR_get_output_ex, 0},
    {"_epicR_mvrnormArma", (DL_FUNC) &_epicR_mvrnormArma, 3},
    {"_epicR_Xrexp", (DL_FUNC) &_epicR_Xrexp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_epicR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
