init_session()
run()
all_events_raw <- Cget_all_events_matrix()
all_events <- as.data.frame(all_events_raw)
COPD_inc_events <- subset (all_events, event ==4)
View(COPD_inc_events)
ggplot2::qplot(COPD_inc_events $gold, geom="histogram")

COPD_prev_events <- subset (all_events, local_time==0 & gold != 0)
View (COPD_prev_events)
ggplot2::qplot(COPD_prev_events$gold, geom="histogram")
terminate_session()
