# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cset_settings_var <- function(name, value) {
    .Call('epicR_Cset_settings_var', PACKAGE = 'epicR', name, value)
}

Cget_settings <- function() {
    .Call('epicR_Cget_settings', PACKAGE = 'epicR')
}

Cget_version <- function() {
    .Call('epicR_Cget_version', PACKAGE = 'epicR')
}

Cget_runtime_stats <- function() {
    .Call('epicR_Cget_runtime_stats', PACKAGE = 'epicR')
}

Xrexp <- function(n, rate) {
    .Call('epicR_Xrexp', PACKAGE = 'epicR', n, rate)
}

Cget_inputs <- function() {
    .Call('epicR_Cget_inputs', PACKAGE = 'epicR')
}

Cset_input_var <- function(name, value) {
    .Call('epicR_Cset_input_var', PACKAGE = 'epicR', name, value)
}

get_sample_output <- function(year, sex) {
    .Call('epicR_get_sample_output', PACKAGE = 'epicR', year, sex)
}

Cget_agent <- function(id) {
    .Call('epicR_Cget_agent', PACKAGE = 'epicR', id)
}

Cget_smith <- function() {
    .Call('epicR_Cget_smith', PACKAGE = 'epicR')
}

Ccreate_agents <- function() {
    .Call('epicR_Ccreate_agents', PACKAGE = 'epicR')
}

Cget_output <- function() {
    .Call('epicR_Cget_output', PACKAGE = 'epicR')
}

Cget_output_ex <- function() {
    .Call('epicR_Cget_output_ex', PACKAGE = 'epicR')
}

Cget_event <- function(i) {
    .Call('epicR_Cget_event', PACKAGE = 'epicR', i)
}

Cget_n_events <- function() {
    .Call('epicR_Cget_n_events', PACKAGE = 'epicR')
}

Cget_agent_events <- function(id) {
    .Call('epicR_Cget_agent_events', PACKAGE = 'epicR', id)
}

Cget_events_by_type <- function(event_type) {
    .Call('epicR_Cget_events_by_type', PACKAGE = 'epicR', event_type)
}

Cget_all_events <- function() {
    .Call('epicR_Cget_all_events', PACKAGE = 'epicR')
}

Cget_all_events_matrix <- function() {
    .Call('epicR_Cget_all_events_matrix', PACKAGE = 'epicR')
}

Callocate_resources <- function() {
    .Call('epicR_Callocate_resources', PACKAGE = 'epicR')
}

Cget_pointers <- function() {
    .Call('epicR_Cget_pointers', PACKAGE = 'epicR')
}

Cdeallocate_resources <- function() {
    .Call('epicR_Cdeallocate_resources', PACKAGE = 'epicR')
}

Cdeallocate_resources2 <- function() {
    .Call('epicR_Cdeallocate_resources2', PACKAGE = 'epicR')
}

Cinit_session <- function() {
    .Call('epicR_Cinit_session', PACKAGE = 'epicR')
}

Cmodel <- function(max_n_agents) {
    .Call('epicR_Cmodel', PACKAGE = 'epicR', max_n_agents)
}

